import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


// setup font
const inter = Inter({ subsets: ["latin"] });


// Defines SEO metadata for the page
export const metadata: Metadata = {
  title: "Create Llama App",
  description: "Generated by create-llama",
};


// Creates a base layout component that wraps all pages
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}


// Steps to Enable Tailwind CSS in Next.js
// Required Files:
// tailwind.config.ts/js - Configuration
// postcss.config.js - PostCSS setup
// globals.css - Tailwind directives